### ISSUE TITLE
Possible bug updating MaxMind GeoLite2 file at midnight (v5.0.1)

### ISSUE THREAD

**Issue by erikgeurts** [revive-adserver/revive-adserver#1126]
There appears to be a problem with the code in v5.0.1 that is supposed to update the GeoLite file at midnight (if a new file is available from MaxMind).

This is what gets logged:

```
PHP Fatal error:  Uncaught Error: Class 'RV_Plugins\geoTargeting\rvMaxMindGeoIP2\MaxMindGeoLite2Downloader' not found in /var/www/virtual/{path_to_revive_adserver}plugins/geoTargeting/rvMaxMindGeoIP2/lib/MaxMindGeoIP2Maintenance.php:23
Stack trace:
#0 /var/www/virtual/{path_to_revive_adserver}lib/OA/Task/Runner.php(46): RV_Plugins\geoTargeting\rvMaxMindGeoIP2\MaxMindGeoIP2Maintenance->run()
#1 /var/www/virtual/{path_to_revive_adserver}lib/OX/Maintenance/Statistics.php(210): OA_Task_Runner->runTasks()
#2 /var/www/virtual/{path_to_revive_adserver}lib/OX/Maintenance.php(154): OX_Maintenance_Statistics->run()
#3 /var/www/virtual/{path_to_revive_adserver}lib/OX/Maintenance.php(108): OX_Maintenance->_runMSE()
#4 /var/www/virtual/{path_to_revive_adserver}scripts/maintenance/maintenance.php(50): OX_Maintenance->run()
#5 /var/www/virtual/{path_to_revive_adserver}maintenance/maintenance.php(22): require_once('/va in /var/www/virtual/{path_to_revive_adserver}plugins/geoTargeting/rvMaxMindGeoIP2/lib/MaxMindGeoIP2Maintenance.php on line 23

```

**Comment by erikgeurts** [comment]
Checked this in the v5.0.2 RC1 and confirmed it's working correctly again (as in: the GeoLite2 file got updated at midnight).
