### ISSUE TITLE
Tokenizer not listed as required extension

### ISSUE THREAD

**Issue by spantaleev** [revive-adserver/revive-adserver#1399]
I'm running Revive Adserver in a container (using PHP 8.1) built from a `Dockerfile` that looks somewhat like this:

```Dockerfile
FROM docker.io/alpine:3.16.2

WORKDIR /var/www/html

RUN apk add --no-cache curl ca-certificates openssl tini && update-ca-certificates --fresh

RUN apk add --no-cache \
        nginx \
        gzip \
        php81 \
        php81-dom \
        php81-ctype \
        php81-curl \
        php81-fpm \
        php81-gd \
        php81-intl \
        php81-json \
        php81-mbstring \
        php81-mysqli \
        php81-mysqlnd \
        php81-opcache \
        php81-pdo \
        php81-pdo_mysql \
        php81-posix \
        php81-session \
        php81-xml \
        php81-iconv \
        php81-phar \
        php81-openssl \
        php81-zlib \
        php81-zip

RUN wget -qO- https://download.revive-adserver.com/revive-adserver-5.4.1.tar.gz | tar xz --strip 1 \
    && chown -R nobody:nobody .

RUN chown nobody: -R /var/lib/nginx

COPY nginx/nginx.conf /etc/nginx/nginx.conf

RUN mkdir -p /run/nginx

EXPOSE 80

CMD php-fpm81 && nginx -g 'daemon off;'

ENTRYPOINT ["/sbin/tini", "--"]
```

I use a custom entrypoint for starting, etc., but it's probably not relevant here at all.

I'm then getting an error like this whenever I try to hit the web UI:

```
2022/10/05 05:59:18 [error] 17#17: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Undefined constant "T_COMMENT" in /var/www/html/lib/OX/Util/CodeMunger.php:22
Stack trace:
#0 /var/www/html/lib/OX/Extension/deliveryLog/Setup.php(15): require_once()
#1 /var/www/html/lib/OX/Plugin/PluginManager.php(14): require_once('...')
#2 /var/www/html/lib/OX/Plugin/PluginExport.php(13): require_once('...')
#3 /var/www/html/lib/OA/Upgrade/UpgradePluginImport.php(13): require_once('...')
#4 /var/www/html/lib/OX/Admin/UI/Install/InstallUtils.php(13): require_once('...')
#5 /var/www/html/lib/OA/Upgrade/EnvironmentManager.php(36): require_once('...')
#6 /var/www/html/lib/OA/Permission.php(18): require_once('...')
#7 /var/www/html/lib/OA/Dll.php(18): require_once('...')
#8 /var/www/html/lib/OA/Admin/Template.php(17): require_once('...')
#9 /var/www/html/lib/OA/Admin/UI.php(13): require_once('...')
#10 /var/www/html/www/admin/lib-gui.inc.php(18): require_once('...')
#11 /var/www/html/www/admin/config.php(17): require_once('...'
```

It's failing here: https://github.com/revive-adserver/revive-adserver/blob/42b0cdd0976b2c394eca7c4601169e1aae76a86e/lib/OX/Util/CodeMunger.php#L22

It doesn't seem like `T_COMMENT` is defined on PHP 8.1.

Commenting out this `define` line makes Revive Adserver work. I'm not sure if anything else breaks long-term, though.

**Comment by mbeccati** [comment]
Interesting. The tokenizer extension is built-in, but it apparently it is not enabed in your Docker image. Your issue can be solved just by adding it in the Dockerfile.

We will need to add it as requirement and/or avoid loading libraries that depend on it if not necessary.

**Comment by spantaleev** [comment]
Ah, I see!

To have tokenizer support in Alpine's PHP build, one needs to also install the `phpXX-tokenizer` package (`php81-tokenizer`, in my case).

Having done that, I no longer need the `CodeMunger.php` workaround.

Feel free to close this issue, unless you still need it as a reminder to update some documentaiton, etc.
